name: My First Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job1 running"
      - run: date

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job2 running"
      - run: date

  job3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job3 running"
      - run: date

  job4:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I am job 4"