name: My First Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - run: python --version
      - run: pip --version

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job2 running"
      - run: date

  job3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job3 running"
      - run: date

  job4:
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - run: echo "I am job 4"